<?php
App::uses('AppModel', 'Model');
/**
 * Condition Model
 *
 * @property Module $Module
 * @property Group $Group
 * @property User $User
 */
class Condition extends AppModel {
	
	public $actsAs = array('Containable');

//Define Artefact Types
    const CONDITION_TYPE_USER = 1; //This has been created by a user through GUI.
    const CONDITION_TYPE_SYSTEM = 2; //This has been generated by an external system.

/**
 * Display field
 *
 * @var string
 */
	public $displayField = 'name';


	//The Associations below have been created with all possible keys, those that are not needed can be removed

/**
 * belongsTo associations
 *
 * @var array
 */
    public $hasAndBelongsToMany = array(
        'Rule' => array(
            'className' => 'Rule',
            'joinTable' => 'rule_conditions',
            'foreignKey' => 'condition_id',
            'associationForeignKey' => 'rule_id',
            'unique' => 'keepExisting',
            'conditions' => '',
            'fields' => '',
            'order' => '',
            'limit' => '',
            'offset' => '',
            'finderQuery' => '',
            'deleteQuery' => '',
            'insertQuery' => ''
        ),
        'Action' => array(
            'className' => 'Action',
            'joinTable' => 'action_conditions',
            'foreignKey' => 'condition_id',
            'associationForeignKey' => 'action_id',
            'unique' => 'keepExisting',
            'conditions' => '',
            'fields' => '',
            'order' => '',
            'limit' => '',
            'offset' => '',
            'finderQuery' => '',
            'deleteQuery' => '',
            'insertQuery' => ''
        ),
        'DimensionVerb' => array(
            'className' => 'DimensionVerb',
            'joinTable' => 'dimension_verb_conditions',
            'foreignKey' => 'condition_id',
            'associationForeignKey' => 'dimension_verb_id',
            'unique' => 'keepExisting',
            'conditions' => '',
            'fields' => '',
            'order' => '',
            'limit' => '',
            'offset' => '',
            'finderQuery' => '',
            'deleteQuery' => '',
            'insertQuery' => ''
        )
    );

    public function get_rule_conditions($rule_id) {
        return $this->Rule->find('all', array(
        	'recursive' => 1,
            'conditions' => array(
                'Rule.id' => $rule_id
            ),
            'contain' => array(
                'Condition' => array(
                    'fields' => array('Condition.id', 'Condition.name'),
                )
            ),
        ));
    }

}
