<h1>Modules<i class="icon-question-sign"></i></h1>
<p>Modules are instances of a tool (
    <?php echo $this->Html->link('artefact', array('controller' => 'Conditions', 'action' => 'help', 4)); ?>
    ) that are generated by a system. For example each time a forum area is created this
    is an instance of the Forum tool.</p>